-----------------------------------------------------------------------------------------------------------------------------------------------
-- View geral de fichas, que vai ser usada nas outras views
CREATE OR REPLACE VIEW V_FICHAS AS
  SELECT NUMERO, DATACRIACAO, TIPO, CATEGERRO, TOTPRO, REV_PROGRAMACAO,
         (SELECT COUNT(*) FROM RNC WHERE FICHAORIGEM = FICHAS.NUMERO) AS NUMERO_ERROS,
         (SELECT NVL(SUM((SELECT SUM(TOTPRO) FROM FICHAS F2 WHERE F2.NUMERO = RNC.FICHA)), 0) FROM RNC WHERE FICHAORIGEM = FICHAS.NUMERO) AS HORAS_CORRECAO
     FROM FICHAS 
     WHERE
        FICHAS.DATACRIACAO > TO_DATE('01/01/2013', 'DD/MM/YYYY') AND
        FICHAS.STATUS = 7 AND -- Encerradas
        FICHAS.REV_PROGRAMACAO IS NOT NULL AND -- NÃ£o sei como aconteceu
        FICHAS.TOTPRO BETWEEN 60 AND 20 * 60 -- Removedor de outliers
        
;
SELECT * FROM V_FICHAS
        
;
CREATE OR REPLACE VIEW V_CHART_HISTORICO_INCIDENTES AS
  SELECT 'SICLA' AS MODEL, SERIES, X, Y FROM (
    SELECT DECODE(CATEGERRO, 0, 'Indefinido', 1, 'Levantamento', 2, 'Análise', 3, 'Produção', 4, 'Geração', 5, 'Entrega', 6, 'Uso sistema', 7, 'Ambiente', CATEGERRO) AS SERIES, TO_CHAR(DATACRI, 'YYYY-MM') AS X, COUNT(*) AS Y FROM ITEMPED WHERE TIPO = 1 AND DATACRI >= TO_DATE('01/01/2012', 'DD/MM/YYYY') GROUP BY CATEGERRO, TO_CHAR(DATACRI, 'YYYY-MM') ORDER BY TO_CHAR(DATACRI, 'YYYY-MM')
  )
;
CREATE OR REPLACE VIEW V_CHART_RELACAO_REVISAO AS
  SELECT MODEL, SERIES, TO_CHAR(MIN(X), '999990.990')||'-'||TO_CHAR(MAX(X), '999990.990') AS X, TO_CHAR(AVG(Y), '999990.990') AS Y, PERIODO FROM (
    SELECT 'SICLA' AS MODEL, 'Número de erros gerados pelas fichas' AS SERIES, RAZAO_REVISAO AS X, RAZAO_CORRECAO AS Y, PERIODO FROM (
      SELECT TO_CHAR(F.DATACRIACAO, 'YYYY-MM') AS PERIODO, F.REV_PROGRAMACAO / F.TOTPRO * 100 AS RAZAO_REVISAO, F.HORAS_CORRECAO / F.TOTPRO * 100 AS RAZAO_CORRECAO
         FROM V_FICHAS F
         ORDER BY PERIODO, RAZAO_REVISAO
      )
    ORDER BY X
  ) GROUP BY MODEL, SERIES, PERIODO, FLOOR(X / 20)
  ORDER BY X;
;
CREATE OR REPLACE VIEW V_CHART_RELACAO_REVISAO_INCID AS
  SELECT MODEL, SERIES, TO_CHAR(MIN(X), '999990.990')||'-'||TO_CHAR(MAX(X), '999990.990') AS X, SUM(Y) AS Y, PERIODO FROM (
    SELECT 'SICLA' AS MODEL, 'Número de erros gerados pelas fichas' AS SERIES, RAZAO_REVISAO AS X, NUMERO_ERROS AS Y, PERIODO FROM (
      SELECT TO_CHAR(DATACRIACAO, 'YYYY-MM') AS PERIODO, REV_PROGRAMACAO / TOTPRO * 100 AS RAZAO_REVISAO, NUMERO_ERROS
         FROM V_FICHAS
         ORDER BY PERIODO, NUMERO_ERROS
      )
    ORDER BY X
  ) GROUP BY MODEL, SERIES, PERIODO, FLOOR(X / 20)
  ORDER BY X;
  SELECT * FROM V_CHART_RELACAO_REVISAO_INCID
;  
select * from V_CHART_RELACAO_REVISAO_INCID ORDER BY PERIODO, X
  
;
CREATE OR REPLACE VIEW V_CHART_CLASSIF_INCIDENTES AS
  SELECT 'SICLA' AS MODEL, 'Incidentes' AS SERIES, X, Y, PERIODO FROM (
    SELECT DECODE(CATEGERRO, 0, 'Indefinido', 1, 'Levantamento', 2, 'AnÃ¡lise', 3, 'ProduÃ§Ã£o', 4, 'GeraÃ§Ã£o', 5, 'Entrega', 6, 'Uso sistema', 7, 'Ambiente', CATEGERRO) AS X, COUNT(*) AS Y, TO_CHAR(DATACRI, 'YYYY-MM') AS PERIODO FROM ITEMPED WHERE TIPO = 1 GROUP BY TO_CHAR(DATACRI, 'YYYY-MM'), CATEGERRO ORDER BY COUNT(*) DESC
  )
;
CREATE OR REPLACE VIEW V_CHART_TOTAL_HORAS_IMPLEM AS
  SELECT 'SICLA' AS MODEL, 'Horas' AS SERIES, 'Horas' AS X, Y, PERIODO FROM (
    SELECT FLOOR(SUM(MINUTOS) / 60) AS Y, TO_CHAR(DATACRIACAO, 'YYYY-MM') AS PERIODO FROM MOVIMENTOS
      INNER JOIN FICHAS
         ON MOVIMENTOS.FICHA = FICHAS.NUMERO
      WHERE FICHAS.TIPO IN (2, 4, 7)
      GROUP BY TO_CHAR(DATACRIACAO, 'YYYY-MM')
  )
;
CREATE OR REPLACE VIEW V_CHART_TOTAL_HORAS_INCID AS
  SELECT 'SICLA' AS MODEL, 'Horas' AS SERIES, 'Horas' AS X, Y, PERIODO FROM (
    SELECT FLOOR(SUM(MINUTOS) / 60) AS Y, TO_CHAR(DATACRIACAO, 'YYYY-MM') AS PERIODO FROM MOVIMENTOS
      INNER JOIN FICHAS
         ON MOVIMENTOS.FICHA = FICHAS.NUMERO
      WHERE FICHAS.TIPO IN (1, 3)
      GROUP BY TO_CHAR(DATACRIACAO, 'YYYY-MM')
  )
;