-----------------------------------------------------------------------------------------------------------------------------------------------
-- Dropa views antigas
DROP VIEW V_CHART_RELACAO_REVISAO;
DROP VIEW V_CHART_HISTORICO_INCIDENTES;
-----------------------------------------------------------------------------------------------------------------------------------------------
-- View geral de fichas, que vai ser usada nas outras views
CREATE OR REPLACE VIEW V_FICHAS AS
  SELECT NUMERO, DATACRIACAO, TIPO, CATEGERRO, TOTPRO, REV_PROGRAMACAO,
         (SELECT COUNT(*) FROM RNC WHERE FICHAORIGEM = V_FICHAS.NUMERO) AS NUMERO_ERROS,
         (SELECT NVL(SUM((SELECT SUM(TOTPRO) FROM V_FICHAS F2 WHERE F2.NUMERO = RNC.FICHA)), 0) FROM RNC WHERE FICHAORIGEM = V_FICHAS.NUMERO) AS HORAS_CORRECAO
     FROM V_FICHAS 
     WHERE
        V_FICHAS.DATACRIACAO > TO_DATE('01/01/2013', 'DD/MM/YYYY') AND
        V_FICHAS.STATUS = 7 AND -- Encerradas
        V_FICHAS.REV_PROGRAMACAO IS NOT NULL AND -- N�o sei como aconteceu
        V_FICHAS.TOTPRO > 60 * 3 -- Removedor de outliers
;
CREATE OR REPLACE VIEW V_CHART_TOTAL_HORAS AS
  SELECT 'SICLA' AS MODEL, TIPO AS SERIES, PERIODO AS X, HORAS AS Y FROM V_HORAS
  ORDER BY SERIES, X
;
-----------------------------------------------------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW V_CHART_RELACAO_REVISAO_INCID AS
  SELECT MODEL, SERIES, TO_CHAR(MIN(X), '999990.990')||'-'||TO_CHAR(MAX(X), '999990.990') AS X, SUM(Y) AS Y, PERIODO FROM (
    SELECT 'SICLA' AS MODEL, 'N�mero de erros gerados pelas fichas' AS SERIES, RAZAO_REVISAO AS X, NUMERO_ERROS AS Y, PERIODO FROM (
      SELECT TO_CHAR(DATACRIACAO, 'YYYY-MM') AS PERIODO, REV_PROGRAMACAO / TOTPRO * 100 AS RAZAO_REVISAO, NUMERO_ERROS
         FROM V_FICHAS
         ORDER BY PERIODO, NUMERO_ERROS
      )
    ORDER BY X
  ) GROUP BY MODEL, SERIES, PERIODO, FLOOR(X / 10)
  ORDER BY X;
  
;
CREATE OR REPLACE VIEW V_CHART_CLASSIF_INCIDENTES AS
  SELECT 'SICLA' AS MODEL, 'Incidentes' AS SERIES, X, Y, PERIODO FROM (
    SELECT DECODE(CATEGERRO, 0, 'Indefinido', 1, 'Levantamento', 2, 'An�lise', 3, 'Produ��o', 4, 'Gera��o', 5, 'Entrega', 6, 'Uso sistema', 7, 'Ambiente', CATEGERRO) AS X, COUNT(*) AS Y, TO_CHAR(DATACRI, 'YYYY-MM') AS PERIODO FROM ITEMPED WHERE TIPO = 1 GROUP BY TO_CHAR(DATACRI, 'YYYY-MM'), CATEGERRO ORDER BY COUNT(*) DESC
  )
;
CREATE OR REPLACE VIEW V_CHART_TOTAL_HORAS_IMPLEM AS
  SELECT 'SICLA' AS MODEL, 'Horas' AS SERIES, 'Horas' AS X, Y, PERIODO FROM (
    SELECT FLOOR(SUM(MINUTOS) / 60) AS Y, TO_CHAR(DATACRIACAO, 'YYYY-MM') AS PERIODO FROM MOVIMENTOS
      INNER JOIN V_FICHAS
         ON MOVIMENTOS.FICHA = V_FICHAS.NUMERO
      WHERE V_FICHAS.TIPO = 'Implenta��o'
      GROUP BY TO_CHAR(DATACRIACAO, 'YYYY-MM')
  )
;
CREATE OR REPLACE VIEW V_CHART_TOTAL_HORAS_INCID AS
  SELECT 'SICLA' AS MODEL, 'Horas' AS SERIES, 'Horas' AS X, Y, PERIODO FROM (
    SELECT FLOOR(SUM(MINUTOS) / 60) AS Y, TO_CHAR(DATACRIACAO, 'YYYY-MM') AS PERIODO FROM MOVIMENTOS
      INNER JOIN V_FICHAS
         ON MOVIMENTOS.FICHA = V_FICHAS.NUMERO  
      WHERE V_FICHAS.TIPO = 'Corre��o'
      GROUP BY TO_CHAR(DATACRIACAO, 'YYYY-MM')
  )
;
CREATE OR REPLACE VIEW V_CHART_TEMPO_REVISAO_FICHAS AS
  SELECT MODEL, SERIES, TO_CHAR(MIN(X), '999990.990')||'-'||TO_CHAR(MAX(X), '999990.990') AS X, SUM(Y) AS Y, PERIODO FROM (
    SELECT 'SICLA' AS MODEL, 'N�mero de fichas' AS SERIES, RAZAO_REVISAO AS X, NUMERO_FICHAS AS Y, PERIODO FROM (
        SELECT TO_CHAR(DATACRIACAO, 'YYYY-MM') AS PERIODO, REV_PROGRAMACAO / TOTPRO * 100 AS RAZAO_REVISAO, 1 AS NUMERO_FICHAS FROM V_FICHAS
      )
    ORDER BY X
  ) GROUP BY MODEL, SERIES, PERIODO, FLOOR(X / 10)
  ORDER BY X;
;
CREATE OR REPLACE VIEW V_HORAS AS
  SELECT FLOOR(SUM(MINUTOS) / 60) AS HORAS, TIPO, PERIODO FROM (
    SELECT MINUTOS, DECODE(TIPO, 1, 'Corre��o', 3, 'Corre��o', 2, 'Implementa��o', 4, 'Implementa��o', 7, 'Implementa��o') AS TIPO, TO_CHAR(DATACRIACAO, 'YYYY-MM') AS PERIODO FROM MOVIMENTOS
          INNER JOIN FICHAS
             ON MOVIMENTOS.FICHA = FICHAS.NUMERO
          WHERE FICHAS.TIPO IN (1, 2, 3, 4, 7) AND DATACRIACAO > TO_DATE('01/01/2013', 'DD/MM/YYYY')
    )
      GROUP BY TIPO, PERIODO
;


    
        SELECT TOTPRO, REV_PROGRAMACAO, TO_CHAR(DATACRIACAO, 'YYYY-MM') AS PERIODO, REV_PROGRAMACAO / TOTPRO * 100 AS RAZAO_REVISAO, 1 AS NUMERO_FICHAS FROM V_FICHAS WHERE TO_CHAR(DATACRIACAO, 'YYYY-MM') = '2015-03'
    ORDER BY RAZAO_REVISAO 