-----------------------------------------------------------------------------------------------------------------------------------------------
-- Dropa views antigas
DROP VIEW V_CHART_RELACAO_REVISAO;
DROP VIEW V_CHART_HISTORICO_INCIDENTES;
DROP VIEW V_CHART_TOTAL_HORAS_IMPLEM;
DROP VIEW V_CHART_TOTAL_HORAS_INCID;
-----------------------------------------------------------------------------------------------------------------------------------------------
-- View geral de fichas, que vai ser usada nas outras views
CREATE OR REPLACE VIEW V_FICHAS AS
  SELECT NUMERO, DATACRIACAO, TO_CHAR(DATACRIACAO, 'YYYY-MM') AS PERIODO, TIPO, CATEGERRO, TOTPRO, REV_PROGRAMACAO, TOTPRO + REV_PROGRAMACAO AS TOTAL_MINUTOS,
         (SELECT COUNT(*) FROM RNC WHERE FICHAORIGEM = FICHAS.NUMERO) AS NUMERO_ERROS,
         (SELECT NVL(SUM((SELECT SUM(TOTPRO) FROM FICHAS F2 WHERE F2.NUMERO = RNC.FICHA)), 0) FROM RNC WHERE FICHAORIGEM = FICHAS.NUMERO) AS HORAS_CORRECAO
     FROM FICHAS 
     WHERE
        FICHAS.DATACRIACAO > TO_DATE('01/01/2013', 'DD/MM/YYYY') AND
        FICHAS.STATUS = 7 AND -- Encerradas
        FICHAS.REV_PROGRAMACAO IS NOT NULL AND -- Não sei como aconteceu
        FICHAS.TOTPRO > 60 * 3 -- Removedor de outliers
;
CREATE OR REPLACE VIEW V_HORAS AS
  SELECT FLOOR(SUM(MINUTOS) / 60) AS HORAS, TIPO, PERIODO FROM (
    SELECT TOTAL_MINUTOS AS MINUTOS, DECODE(TIPO, 1, 'Correção', 3, 'Correção', 2, 'Implementação', 4, 'Implementação', 7, 'Implementação') AS TIPO, TO_CHAR(DATACRIACAO, 'YYYY-MM') AS PERIODO FROM V_FICHAS
          WHERE TIPO IN (1, 2, 3, 4, 7) AND DATACRIACAO > TO_DATE('01/01/2013', 'DD/MM/YYYY')
    )
      GROUP BY TIPO, PERIODO
;
-----------------------------------------------------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW V_CHART_TOTAL_HORAS AS
  SELECT 'SICLA' AS MODEL, TIPO AS SERIES, PERIODO AS X, HORAS AS Y FROM V_HORAS
  ORDER BY SERIES, X
;
CREATE OR REPLACE VIEW V_CHART_RELACAO_REVISAO_INCID AS
  SELECT MODEL, SERIES, TO_CHAR(MIN(X), '999990.990')||'-'||TO_CHAR(MAX(X), '999990.990') AS X, SUM(Y) AS Y, PERIODO FROM (
    SELECT 'SICLA' AS MODEL, 'Número de erros gerados pelas fichas' AS SERIES, RAZAO_REVISAO AS X, NUMERO_ERROS AS Y, PERIODO FROM (
      SELECT PERIODO, REV_PROGRAMACAO / TOTPRO * 100 AS RAZAO_REVISAO, NUMERO_ERROS
         FROM V_FICHAS
         ORDER BY PERIODO, NUMERO_ERROS
      )
    ORDER BY X
  ) GROUP BY MODEL, SERIES, PERIODO, FLOOR(X / 10)
  ORDER BY X
 
;
CREATE OR REPLACE VIEW V_CHART_CLASSIF_INCIDENTES AS
  SELECT 'SICLA' AS MODEL, 'Incidentes' AS SERIES, X, Y, PERIODO FROM (
    SELECT DECODE(CATEGERRO, 0, 'Indefinido', 1, 'Levantamento', 2, 'Análise', 3, 'Produção', 4, 'Geração', 5, 'Entrega', 6, 'Uso sistema', 7, 'Ambiente', CATEGERRO) AS X, COUNT(*) AS Y, TO_CHAR(DATACRI, 'YYYY-MM') AS PERIODO FROM ITEMPED WHERE TIPO = 1 GROUP BY TO_CHAR(DATACRI, 'YYYY-MM'), CATEGERRO ORDER BY COUNT(*) DESC
  )
;
CREATE OR REPLACE VIEW V_CHART_TEMPO_REVISAO_FICHAS AS
  SELECT MODEL, SERIES, TO_CHAR(MIN(X), '999990.9')||'-'||TO_CHAR(MAX(X), '999990.9') AS X, TO_CHAR(SUM(Y) / (SELECT COUNT(*) FROM V_FICHAS I WHERE I.PERIODO = O.PERIODO), '999990.990') AS Y, PERIODO FROM (
    SELECT 'SICLA' AS MODEL, 'Número de fichas' AS SERIES, RAZAO_REVISAO AS X, NUMERO_FICHAS AS Y, PERIODO FROM (
        SELECT PERIODO, REV_PROGRAMACAO / TOTPRO * 100 AS RAZAO_REVISAO, 1 AS NUMERO_FICHAS FROM V_FICHAS
      )
    WHERE RAZAO_REVISAO < 100  
    ORDER BY X
  ) O
  GROUP BY MODEL, SERIES, PERIODO, FLOOR(X / 10)
  ORDER BY X
;